[tools]
terraform      = "1.9.8"
pre-commit     = "4.2.0"
terraform-docs = "0.20.0"
trivy          = "0.62.1"
tflint         = "0.57.0"
gitleaks       = "8.26.0"

[tasks]
[tasks.fmt]
run = "terraform fmt -recursive"

[tasks.pre-commit]
run = "pre-commit run --all-files --show-diff-on-failure"

[tasks.trivy]
run = "trivy fs --scanners misconfig,secret,vuln ."
